#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_SMTP")]
	public partial class DB_SMTPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_T_AJUKAN_SURAT(TBL_T_AJUKAN_SURAT instance);
    partial void UpdateTBL_T_AJUKAN_SURAT(TBL_T_AJUKAN_SURAT instance);
    partial void DeleteTBL_T_AJUKAN_SURAT(TBL_T_AJUKAN_SURAT instance);
    #endregion
		
		public DB_SMTPDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_SMTPConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SMTPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SMTPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SMTPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_SMTPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_T_AJUKAN_SURAT> TBL_T_AJUKAN_SURATs
		{
			get
			{
				return this.GetTable<TBL_T_AJUKAN_SURAT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_AJUKAN_SURAT")]
	public partial class TBL_T_AJUKAN_SURAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nama_lengkap;
		
		private string _nik;
		
		private string _alamat;
		
		private string _email;
		
		private string _jenis_surat;
		
		private string _tujuan;
		
		private string _dokumen_path;
		
		private string _nomor_surat;
		
		private System.Nullable<int> _status;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private System.Nullable<System.DateTime> _updated_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnama_lengkapChanging(string value);
    partial void Onnama_lengkapChanged();
    partial void OnnikChanging(string value);
    partial void OnnikChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onjenis_suratChanging(string value);
    partial void Onjenis_suratChanged();
    partial void OntujuanChanging(string value);
    partial void OntujuanChanged();
    partial void Ondokumen_pathChanging(string value);
    partial void Ondokumen_pathChanged();
    partial void Onnomor_suratChanging(string value);
    partial void Onnomor_suratChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onupdated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_dateChanged();
    #endregion
		
		public TBL_T_AJUKAN_SURAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_lengkap", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nama_lengkap
		{
			get
			{
				return this._nama_lengkap;
			}
			set
			{
				if ((this._nama_lengkap != value))
				{
					this.Onnama_lengkapChanging(value);
					this.SendPropertyChanging();
					this._nama_lengkap = value;
					this.SendPropertyChanged("nama_lengkap");
					this.Onnama_lengkapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nik", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nik
		{
			get
			{
				return this._nik;
			}
			set
			{
				if ((this._nik != value))
				{
					this.OnnikChanging(value);
					this.SendPropertyChanging();
					this._nik = value;
					this.SendPropertyChanged("nik");
					this.OnnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_surat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jenis_surat
		{
			get
			{
				return this._jenis_surat;
			}
			set
			{
				if ((this._jenis_surat != value))
				{
					this.Onjenis_suratChanging(value);
					this.SendPropertyChanging();
					this._jenis_surat = value;
					this.SendPropertyChanged("jenis_surat");
					this.Onjenis_suratChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tujuan", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string tujuan
		{
			get
			{
				return this._tujuan;
			}
			set
			{
				if ((this._tujuan != value))
				{
					this.OntujuanChanging(value);
					this.SendPropertyChanging();
					this._tujuan = value;
					this.SendPropertyChanged("tujuan");
					this.OntujuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dokumen_path", DbType="VarChar(255)")]
		public string dokumen_path
		{
			get
			{
				return this._dokumen_path;
			}
			set
			{
				if ((this._dokumen_path != value))
				{
					this.Ondokumen_pathChanging(value);
					this.SendPropertyChanging();
					this._dokumen_path = value;
					this.SendPropertyChanged("dokumen_path");
					this.Ondokumen_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomor_surat", DbType="VarChar(50)")]
		public string nomor_surat
		{
			get
			{
				return this._nomor_surat;
			}
			set
			{
				if ((this._nomor_surat != value))
				{
					this.Onnomor_suratChanging(value);
					this.SendPropertyChanging();
					this._nomor_surat = value;
					this.SendPropertyChanged("nomor_surat");
					this.Onnomor_suratChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_date
		{
			get
			{
				return this._updated_date;
			}
			set
			{
				if ((this._updated_date != value))
				{
					this.Onupdated_dateChanging(value);
					this.SendPropertyChanging();
					this._updated_date = value;
					this.SendPropertyChanged("updated_date");
					this.Onupdated_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
